name: 'Napptive Catalog push'
author: 'Napptive'
description: 'Push an application into Napptive catalog.'
inputs:
  applicationPath:
    description: 'The path of the application to be uploaded'
    required: true
  namespace:
    description: 'The namespace where the application is going to be uploaded'
    required: true
  applicationName:
    description: 'The name of the application'
    required: true
  tag:
    description: 'The application version'
    required: true
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.applicationPath }}
    - ${{ inputs.namespace }}
    - ${{ inputs.applicationName }}
    - ${{ inputs.tag }}
branding:
  icon: 'play'  
  color: 'blue'